Add pre-commit hook for mypy (#133)
This adds support for running mypy via pre-commit.

Like flake8 and black, mypy is run via Poetry using a [local hook]. This has the
drawback that you need to run `poetry install` before you can use pre-commit
with your project. On other hand, it allows you to manage these tools as
development dependencies in Poetry. The alternative would be to have duplicate
and potentially diverging version pins in the Poetry lock file and the
pre-commit configuration. Also, pinning subdependencies does not appear to be
very practical with pre-commit.

[local hook]: https://pre-commit.com/#repository-local-hooks

The [require_serial] option is enabled like in pre-commit's own mypy mirror. The
rationale for this appears to be performance (see issue 2 in mirrors-mypy).

[require_serial]: https://pre-commit.com/#creating-new-hooks

Set [mypy_path] in the configuration file pointing it to the `src` directory.
This is required to avoid errors about missing imports related to your package
when mypy is invoked on files located outside of the package, such as modules in
the test suite. For example, pre-commit runs mypy on staged files only, so this
would be a common issue with our mypy pre-commit hook.

[mypy_path]: https://mypy.readthedocs.io/en/stable/config_file.html#config-file-import-discovery

This solution is preferred to passing `MYPYPATH` via the pre-commit hook, for
two reasons:

- It is more portable because it does not require `env(1)` to be available.
- It will benefit uses of mypy outside of the pre-commit framework.

Here is an example of an error message resulting from running mypy on a test
module without mypy_path:

```
tests/test_console.py:5:1: error: Skipping analyzing 'cookiecutter_hypermodern_python_instance': found module but no type hints or library stubs  [import]
    from cookiecutter_hypermodern_python_instance import console
    ^
tests/test_console.py:5:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

* Add pre-commit hook for mypy

* Fix pre-commit hook for mypy using `env` (not portable)

* Set mypy_path to the src directory

* Do not set MYPYPATH in pre-commit hook

* Update documentation about mypy configuration with mypy_path

* Update documentation about pre-commit hooks with mypy

cjolowicz/cookiecutter-hypermodern-python-instance#105